package com.imnotpayingforthat.imnotpayingforthat.util;

public interface ErrorCodes {
    String REGISTRATION_FIRSTNAME_MUST_BE_FILLED = "REGISTRATION_FIRSTNAME_MUST_BE_FILLED";
    String REGISTRATION_LASTNAME_MUST_BE_FILLED = "REGISTRATION_LASTNAME_MUST_BE_FILLED";
    String REGISTRATION_EMAIL_MUST_BE_FILLED = "REGISTRATION_EMAIL_MUST_BE_FILLED";
    String REGISTRATION_FAILED = "REGISTRATION_FAILED";
    String REGISTRATION_PASSWORD_NOT_EQUAL = "REGISTRATION_PASSWORD_NOT_EQUAL";
    String REGISTRATION_PASSWORD_MUST_BE_FILLED = "REGISTRATION_PASSWORD_MUST_BE_FILLED";
    String REGISTRATION_CONFIRMPASSWORD_MUST_BE_FILLED = "REGISTRATION_CONFIRMPASSWORD_MUST_BE_FILLED";
}
